# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='catgary',
            field=models.CharField(default='web\u5f00\u53d1/\u540e\u7aef\u5f00\u53d1', max_length=20, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
