# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170815_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=50, verbose_name='\u8001\u5e08\u544a\u8bc9\u4f60'),
        ),
        migrations.AddField(
            model_name='course',
            name='youneed_know',
            field=models.CharField(default='', max_length=50, verbose_name='\u4f60\u9700\u8981\u77e5\u9053\u4ec0\u4e48'),
        ),
    ]
