# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170815_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u8f6e\u64ad\u56fe'),
        ),
    ]
